### ISSUE TITLE
2021.11.9 Checklist

### ISSUE THREAD

**Issue by edqx** [SkeldJS/SkeldJS#27]
### Protocol Changes
- [X] Hello packet
- [X] Host game
- [x] Redirect (?)
- [x] Role Rpcs (?)

### Auth
- [X] DTLS Auth method
- [x] Nonce exchange auth method
- [X] Optional use no auth

### Roles
- [x] Gamedata changes
- [x] Game settings changes
- Role classes
  - [x] Engineer
  - [x] Scientist
  - [x] Guardian Angel
  - [x] Shapeshifter

List subject to change
